game.libretro: update to 2.0.0-Matrix
Fixes the build error:
../src/audio/AudioStream.h:24:10: fatal error: kodi_game_types.h: No such file or directory

See xbmc/xbmc#16453