samba: qualify required gssapi.h
Inconsistent builds with samba 4.16 with the wrong gssapi.h being picked
up. This is a workaround, and being raised upstream.

[1800/2511] Compiling source3/lib/smbd_shim.c
In file included from ../../third_party/heimdal/lib/gssapi/gssapi/gssapi_krb5.h:40,
                 from ../../lib/replace/system/gssapi.h:43,
                 from ../../lib/krb5_wrap/gss_samba.h:27,
                 from ../../auth/kerberos/pac_utils.h:27,
                 from ../../auth/kerberos/gssapi_pac.c:28:
../../third_party/heimdal/lib/gssapi/gssapi/gssapi_oid.h:9:8: error: unknown type name 'GSSAPI_LIB_VARIABLE'
    9 | extern GSSAPI_LIB_VARIABLE gss_OID_desc __gss_krb5_copy_ccache_x_oid_desc;
      |        ^~~~~~~~~~~~~~~~~~~