chailove: Update to 0.28.0 (#552)
Updates to ChaiLove 0.28.0 which fixes an undefined reference to 'process_sinc_neon_asm'.

References:
- https://github.com/libretro/libretro-chailove/issues/322
- https://github.com/libretro/libretro-chailove/releases/tag/0.28.0