Adds a fix for p7zip on GCC10
New GCC throws errors instead of warnings:
  CPP/Common/MyWindows.h:89:43: error: narrowing conversion of
  '-2147024809' from 'LONG' {aka 'int'} to 'unsigned int' [-Wnarrowing]