linux (default, RPi): fix perf build with glibc 2.30
perf build fails because glibc 2.30 includes a gettid() function:

jvmti/jvmti_agent.c:48:21: error: static declaration of 'gettid' follows non-static declaration
   48 | static inline pid_t gettid(void)
      |                     ^~~~~~
In file included from /home/hias/rpi/libreelec-master/build.LibreELEC-RPi4.arm-9.80-devel/toolchain/armv8a-libreelec-linux-gnueabi/sysroot/usr/include/unistd.h:1170,
                 from jvmti/jvmti_agent.c:33:
/home/hias/rpi/libreelec-master/build.LibreELEC-RPi4.arm-9.80-devel/toolchain/armv8a-libreelec-linux-gnueabi/sysroot/usr/include/bits/unistd_ext.h:34:16: note: previous declaration of 'gettid' was here
   34 | extern __pid_t gettid (void) __THROW;
      |                ^~~~~~

This has already been fixed in the 5.3 kernel tree. Add a backport
commit until the fix dribbles down into stable 5.2 or we swtich to 5.3.

Signed-off-by: Matthias Reichl <hias@horus.com>