rpcbind: update to 1.2.6
update 1.2.5 (2018-08-15) to 1.2.6 (2021-05-10)

changelog:
- https://sourceforge.net/projects/rpcbind/files/rpcbind/1.2.6/1.2.6-ChangeLog/download

commit 7fcf2b27097fda927d637835468a83ed1b918001
Author: Roberto Bergantinos Corpas <rbergant@redhat.com>
Date:   Mon May 10 12:53:19 2021 -0400

    network_init: initialize response addrinfo list to NULL

    res pointer is not initialized, if for some reason it does not
    take any value after calling getaddrinfo, we end up causing oops
    when calling freeaddrinfo

    Signed-off-by: Roberto Bergantinos Corpas <rbergant@redhat.com>
    Signed-off-by: Steve Dickson <steved@redhat.com>

commit 7be92b30e47801c651e5316217d1651454653f68
Author: Roberto Bergantinos Corpas <rbergant@redhat.com>
Date:   Mon Nov 16 08:39:36 2020 -0500

    security: dowgrade priority for non-libwrap CALLIT logging

    Use aswell auth.warning for non-libwrap CALLIT logging, otherwise
    we'll broadcast everywhere for a call that is not allowed anyway

    Signed-off-by: Roberto Bergantinos Corpas <rbergant@redhat.com>
    Signed-off-by: Steve Dickson <steved@redhat.com>

commit 4bedceec49c804911770561fb09a4d2641f7d28d
Author: Petr Vorel <pvorel@suse.cz>
Date:   Tue Jun 9 09:44:35 2020 -0400

    man/rpcbind: Mention systemd socket in -h

    and reformat doc a bit.

    Based on Olaf Kirch's patch for openSUSE.

    Signed-off-by: Petr Vorel <pvorel@suse.cz>
    Signed-off-by: Steve Dickson <steved@redhat.com>

commit 3f4259b629ddd6ed3872a2bd2408711b789614da
Author: Petr Vorel <pvorel@suse.cz>
Date:   Thu Jun 4 10:21:27 2020 -0400

    security: Fix typos in debug messages and comments

    Signed-off-by: Petr Vorel <pvorel@suse.cz>
    Signed-off-by: Steve Dickson <steved@redhat.com>

commit 51945ec6fbebd5d5dfa525bd2dda0b950fe4e3bc
Author: Steve Dickson <steved@redhat.com>
Date:   Thu Feb 6 14:18:21 2020 -0500

    network_init: clean up a error path found by a covscan

    Signed-off-by: Steve Dickson <steved@redhat.com>

commit 8bf0ce4a1858b5cd00440e416ecfe0fd74662a01
Author: Mike Gilbert <floppym@gentoo.org>
Date:   Tue Jan 21 11:35:38 2020 -0500

    rpcbind: always use inline rpcsvc constants

    Modern versions of glibc no longer provide the rpcsvc headers, so
    there's very little point in trying to use them.

    Signed-off-by: Mike Gilbert <floppym@gentoo.org>
    Signed-off-by: Steve Dickson <steved@redhat.com>

commit eef835dbae60bc1f162d73369fda88700cf21d6f
Author: Mike Gilbert <floppym@gentoo.org>
Date:   Fri Jan 17 10:06:25 2020 -0500

    rpcbind: configure: fix detection of rpcsvc/mount.h

    If libtirpc is providing rpc/rpc.h, including rpcsvc/mount.h may fail if
    -I/path/to/tirpc is not passed to the compiler.

    Bug: https://bugs.gentoo.org/665222
    Signed-off-by: Mike Gilbert <floppym@gentoo.org>
    Signed-off-by: Steve Dickson <steved@redhat.com>

commit c05401d753fec8ac692299819f32565ffafe2a3d
Author: Steve Dickson <steved@redhat.com>
Date:   Tue Jan 14 14:21:02 2020 -0500

    README: Add where to send bug reports

    Signed-off-by: Steve Dickson <steved@redhat.com>

commit 8d6389fb701cd6b12b9bf0a0359ee2cad2a478ac
Author: Steve Dickson <steved@redhat.com>
Date:   Tue Nov 5 11:02:21 2019 -0500

    Remove BAD_FREE from reply_proc()

    Signed-off-by: Steve Dickson <steved@redhat.com>

commit e915f698cc534aceb774312f9aa2a42b5f457985
Author: Steve Dickson <steved@redhat.com>
Date:   Mon Jul 29 09:45:31 2019 -0400

    rpcinfo: Removed resource leaks from src/util.c

    Signed-off-by: Steve Dickson <steved@redhat.com>

commit a6889bba949b1d7f2d745ba1cb6528492da11d45
Author: Steve Dickson <steved@redhat.com>
Date:   Sat Jul 27 13:54:50 2019 -0400

    Removed resource leaks from src/rpcbind.c

    Signed-off-by: Steve Dickson <steved@redhat.com>

commit fc61ce53bf9e7a099b6356dd88122f60f9a21eda
Author: Amadeusz Sławiński <amade@asmblr.net>
Date:   Thu Sep 26 15:29:19 2019 -0400

    rpcbind: Correct some of includes

    Musl based systems are more pedantic than glibc ones about where we
    include files from. Correct some headers to include proper files.

    In file included from src/rpcb_svc_com.c:45:0:
    /usr/include/sys/poll.h:1:2: warning: #warning redirecting incorrect #include <sys/poll.h> to <poll.h> [-Wcpp]
     #warning redirecting incorrect #include <sys/poll.h> to <poll.h>
      ^~~~~~~

    In file included from src/rpcbind.c:45:0:
    /usr/include/sys/errno.h:1:2: warning: #warning redirecting incorrect #include <sys/errno.h> to <errno.h> [-Wcpp]
     #warning redirecting incorrect #include <sys/errno.h> to <errno.h>
      ^~~~~~~
    In file included from src/rpcbind.c:49:0:
    /usr/include/sys/signal.h:1:2: warning: #warning redirecting incorrect #include <sys/signal.h> to <signal.h> [-Wcpp]
     #warning redirecting incorrect #include <sys/signal.h> to <signal.h>
      ^~~~~~~

    In file included from src/util.c:48:0:
    /usr/include/sys/poll.h:1:2: warning: #warning redirecting incorrect #include <sys/poll.h> to <poll.h> [-Wcpp]
     #warning redirecting incorrect #include <sys/poll.h> to <poll.h>
      ^~~~~~~

    Signed-off-by: Amadeusz Sławiński <amade@asmblr.net>
    Signed-off-by: Steve Dickson <steved@redhat.com>

commit 9a40fb4fb35506f6f1423318ed736caf5e490fb7
Author: Amadeusz Sławiński <amade@asmblr.net>
Date:   Thu Sep 26 15:27:23 2019 -0400

    rpcbind: Add missing includes

    On musl systems there are implicit function declaration warnings due to
    missing string.h include.

    src/pmap_svc.c: In function ‘pmapproc_change’:
    src/pmap_svc.c:225:8: warning: implicit declaration of function ‘memcmp’ [-Wimplicit-function-declaration]
       if (!memcmp(rpcbreg.r_netid, "udp6", 4) ||
            ^~~~~~
    src/pmap_svc.c: In function ‘pmap_netid2ipprot’:
    src/pmap_svc.c:408:6: warning: implicit declaration of function ‘strcmp’ [-Wimplicit-function-declaration]
      if (strcmp(netid, tcptrans) == 0)
          ^~~~~~

    src/warmstart.c: In function ‘read_struct’:
    src/warmstart.c:116:22: warning: implicit declaration of function ‘strerror’; did you mean ‘perror’? [-Wimplicit-function-declaration]
         filename, errno, strerror(errno));
                          ^~~~~~~~
                          perror

    Signed-off-by: Amadeusz Sławiński <amade@asmblr.net>
    Signed-off-by: Steve Dickson <steved@redhat.com>

commit 06a3103a871de29478e499818ef227779c1dd9a6
Author: Steve Dickson <steved@redhat.com>
Date:   Tue Aug 6 13:41:47 2019 -0400

    rpcinfo: Removed overun from src/rpcb_stat.c

    Signed-off-by: Steve Dickson <steved@redhat.com>

commit b5937e1414e1600d788fd1d689b4f64a09422d03
Author: Steve Dickson <steved@redhat.com>
Date:   Thu Sep 5 10:06:18 2019 -0400

    rpcbind: look for an exact match of the ip address for a requested service first

    the rpcbind program returns the first IP address that matches the hint
    IP, i.e.: The first interface found that is UP and on the same network
    as the hint IP address (bestmatch).
    That could be wrong if there are multiple ips in the same subnet for the
    same interface configured.

    For instance output of ip addr:
    ~> ip addr
        inet 10.xxx.xx.133/22 brd 10.xxx.xx.255 scope global mgmt   <------first ip-address which matches the hint
        inet 10.xxx.xx.147/22 scope global eth0     <----actual ip-address where nfs server is configured
        inet 10.xxx.xx.160/22 scope global secondary eth0
    ~>

    rpc mount export: RPC: Timed out
    rpc mount export: RPC: Timed out

    For multiple IP adresses in the same subnet, it should try to find an
    exact match first and only if that fails return the best match.

    Signed-off-by: Thomas Blume <thomas.blume@suse.com>
    Signed-off-by: Steve Dickson <steved@redhat.com>

commit 0bc1c0ae7ce61a7ac8a8e9a9b2086268f011abf0
Author: Steve Dickson <steved@redhat.com>
Date:   Tue Oct 9 09:19:50 2018 -0400

    rpcinfo: Fix stack buffer overflow

    *** buffer overflow detected ***: rpcinfo terminated
    ======= Backtrace: =========
    /lib64/libc.so.6(+0x721af)[0x7ff24c4451af]
    /lib64/libc.so.6(__fortify_fail+0x37)[0x7ff24c4ccdc7]
    /lib64/libc.so.6(+0xf8050)[0x7ff24c4cb050]
    rpcinfo(+0x435f)[0xef3be2635f]
    rpcinfo(+0x1c62)[0xef3be23c62]
    /lib64/libc.so.6(__libc_start_main+0xf5)[0x7ff24c3f36e5]
    rpcinfo(+0x2739)[0xef3be24739]
    ======= Memory map: ========
    ...
    The patch below fixes it.

    Reviewed-by: Chuck Lever <chuck.lever@oracle.com>
    Signed-off-by: Thomas Blume <thomas.blume@suse.com>
    Signed-off-by: Steve Dickson <steved@redhat.com>